
function getWeekSongs() {
    return {
        'TeaSloBoo': [
            {
                dayOfWeek: '1',
                artist: 'Валентин Стрыкало ',
                song: 'Наше лето ',
                cover: 'https://images.genius.com/f5c062b72d4d8abaae472b787d1b133a.1000x1000x1.png',
                youtube: 'http://www.youtube.com/watch?v=VMS30oV8ApE',
                date: '2011-08-04',
                geniusId: '3500910',
                definition: {
                    'ялта': 'курортный и портовый город на Южном берегу Крыма',
                    'август': 'летний месяц',
                    'новую каховку': 'город в Херсонской области Украины, административный центр Каховского района',
                }
            },
            {
                dayOfWeek: '2',
                artist: 'Чиж и Ко ',
                song: 'О любви ',
                cover: 'https://images.genius.com/0c07e8e3eaa58fb65be9e6e61092bdb5.1000x1000x1.png',
                youtube: 'https://www.youtube.com/watch?v=dL-VxP_wbbk',
                date: '',
                geniusId: '4444639',
            },
            {
                dayOfWeek: '3',
                artist: 'Витас ',
                song: 'Опера #2 ',
                cover: 'https://images.genius.com/19cafb9625e8fc8ffa44f3d968d63b1d.600x600x1.jpg',
                youtube: 'http://www.youtube.com/watch?v=Skpra8cva1w',
                date: '2001-03-01',
                geniusId: '2000765',
            },
            {
                dayOfWeek: '4',
                artist: 'Браво ',
                song: 'Это за окном рассвет ',
                cover: 'https://images.genius.com/14b46c227fdcec3064303e3ca56a1613.369x369x1.jpg',
                youtube: 'https://www.youtube.com/watch?v=yLUOwe9f2X8',
                date: '1996-01-01',
                geniusId: '3202398',
                definition: {
                    'декабре': 'зимний месяц',
                }
            },
            {
                dayOfWeek: '5',
                artist: 'Юрий Титов',
                song: 'Понарошку ',
                cover: 'https://images.genius.com/8d61f611912cf19b7c7fe7139738e2f9.999x999x1.jpg',
                youtube: 'https://www.youtube.com/watch?v=sV_ZdWA4m-I',
                date: '2021-04-02',
                geniusId: '6738268',
            },
            {
                dayOfWeek: '6',
                artist: 'Мурат Насыров ',
                song: 'Мальчик хочет в Тамбов ',
                cover: 'https://images.genius.com/408eae0d62337d34df765beecefe0532.500x500x1.jpg',
                youtube: 'http://www.youtube.com/watch?v=EW93pojria8',
                date: '',
                geniusId: '967425',
            },
            {
                dayOfWeek: '7',
                artist: 'Леонид Агутин ',
                song: 'Хоп Хей Лала-лей ',
                cover: '',
                youtube: 'https://www.youtube.com/watch?v=mlhfnvTmaek',
                date: '',
                geniusId: '8833885',
            },
            {
                dayOfWeek: '8',
                artist: 'Верка Сердючка ',
                song: 'Тук, Тук, Тук ',
                cover: 'https://images.genius.com/b4aac1f7d25a82d6107ff8f61978b611.600x600x1.jpg',
                youtube: 'https://www.youtube.com/watch?v=KRVhWPignvU',
                date: '',
                geniusId: '5358526',
            },
            {
                dayOfWeek: '9',
                artist: 'Гости из будущего ',
                song: 'Беги от меня ',
                cover: 'https://images.genius.com/c7b3293744fc4884bd52ff6563494a6c.300x300x1.jpg',
                youtube: 'http://www.youtube.com/watch?v=uD9jluLGS-s',
                date: '',
                geniusId: '4625258',
            },
            {
                dayOfWeek: '10',
                artist: 'Лигалайз ',
                song: 'Будущие мамы ',
                cover: 'https://images.genius.com/cb59d37b4eee9d87a9365cc4023d1c47.1000x1000x1.jpg',
                youtube: 'http://www.youtube.com/watch?v=fNOyqQkzf0Y',
                date: '2006-04-29',
                geniusId: '51895',
                definition: {
                    'rnb': '(англ. сокр.) стиль популярной музыки афроамериканцев, включающий элементы блюза',
                    'vip': '(англ. сокр.) очень важная персона',
                    'перфоманса': 'форма современного искусства, в которой произведения составляют действия художника или группы в определённом месте и времени',
                    'текилы': 'крепкий алкогольный напиток, вид мескаля',
                    'чилаут': 'в англоязычном мире метафорическое обозначение лёгкой академической музыки',
                    'эйфория': 'эмоция и сериал',
                }
            },
            {
                dayOfWeek: '11',
                artist: 'Блестящие ',
                song: 'А я всё летала ',
                cover: 'https://images.genius.com/74b3c61a9056ebf395ece8a6c5a891f4.533x533x1.jpg',
                youtube: 'http://www.youtube.com/watch?v=ywJihN8-bEI',
                date: '',
                geniusId: '3523520',
            },
            {
                dayOfWeek: '12',
                artist: 'Профессор Лебединский ',
                song: 'Я убью тебя, лодочник ',
                cover: '',
                youtube: 'http://www.youtube.com/watch?v=s1mbq2BZbcg',
                date: '',
                geniusId: '8240306',
                definition: {
                    'уключина': 'элемент лодки, гребного судна, для подвижного крепления весла к борту.',
                    'аврору': 'русский крейсер, один из символов Октябрьской революции 1917 года.',
                }
            },
            {
                dayOfWeek: '13',
                artist: 'Аквариум ',
                song: 'Город ',
                cover: 'https://images.genius.com/c2620eb1e8baa619c96a56b0569488ca.999x999x1.jpg',
                youtube: 'https://www.youtube.com/watch?v=0Oe-n8f2Xv8',
                date: '',
                geniusId: '3653144',
            },
            {
                dayOfWeek: '14',
                artist: 'Валерий Леонтьев ',
                song: 'Дельтаплан ',
                cover: 'https://images.genius.com/23150c836aa243e130151474add782e9.999x999x1.jpg',
                youtube: 'https://www.youtube.com/watch?v=AWjr5fMgYSY',
                date: '',
                geniusId: '5217264',
            },
            {
                dayOfWeek: '15',
                artist: 'Владимир Маркин ',
                song: 'Я готов целовать песок ',
                cover: 'https://images.genius.com/779b5a4b03414e4fd29df7b6b47fa663.300x300x1.jpg',
                youtube: 'https://www.youtube.com/watch?v=5MGEQs3-7Yc',
                date: '',
                geniusId: '6665046',
                definition: {
                    'соловьи': 'род птиц из отряда воробьинообразных'
                }
            },
            {
                dayOfWeek: '16',
                artist: 'ДДТ ',
                song: 'Родина ',
                cover: 'https://images.genius.com/b54d824a4a2b399f0a5bf97e1535f823.1000x1000x1.png',
                youtube: 'https://www.youtube.com/watch?v=5DRqD6TznoU',
                date: '',
                geniusId: '2277062',
                definition: {
                    'вороненым': 'покрытый чернью',
                    'лютики': 'род однолетних или многолетних травянистых растений семейства Лютиковые',
                    'плахи': 'помост, на котором совершалась эта казнь',
                }
            },
            {
                dayOfWeek: '17',
                artist: 'Amega ',
                song: 'Лететь ',
                cover: 'https://images.genius.com/c4cf416cf2582a083f0442325c10582f.288x288x1.png',
                youtube: 'http://www.youtube.com/watch?v=Ttk0Pdf6Xos',
                date: '1999-01-01',
                geniusId: '7927924',
            },
            {
                dayOfWeek: '18',
                artist: 'Юрий Антонов ',
                song: 'Я вспоминаю ',
                cover: '',
                youtube: 'http://www.youtube.com/watch?v=fFJj_wYMxqA',
                date: '',
                geniusId: '9245157',
            },
            {
                dayOfWeek: '19',
                artist: 'Мальчишник ',
                song: 'Секс без перерыва ',
                cover: 'https://images.genius.com/5324371888635ce1ce08d931733fc553.544x544x1.png',
                youtube: 'http://www.youtube.com/watch?v=osNuCid0iJo',
                date: '',
                geniusId: '3302112',
                definition: {
                    'бюстгальтера': 'предмет женского нижнего белья, который прикрывает, поддерживает и приподнимает женскую грудь',
                    'дельфин': 'морское млекопитающее',
                    'дэн': '(сокр.) Денис',
                    'мутабор': ' заклинание, превращающее людей в животных и обратно в сказке «Калиф-аист»',
                    'чиксой': 'то же, что девушка',
                }
            },
            {
                dayOfWeek: '20',
                artist: '#2Маши ',
                song: 'Мама, я танцую ',
                cover: 'https://images.genius.com/ff6a672c3d14c10df48de423c7257f44.1000x1000x1.jpg',
                youtube: 'http://www.youtube.com/watch?v=jezU0MUixaY',
                date: '2018-11-13',
                geniusId: '4206523',
                definition: {
                    'босую': 'песня группы #2Маши'
                }
            },
            {
                dayOfWeek: '21',
                artist: 'Любэ ',
                song: 'Атас ',
                cover: 'https://images.genius.com/dad8c9b5396d463e527a5d0dcb308aa6.1000x1000x1.png',
                youtube: 'http://www.youtube.com/watch?v=dw5ToimDJjg',
                date: '1989-10-15',
                geniusId: '9361516',
                definition: {
                    'глеб жеглов': 'один из главных героев сериала «Место встречи изменить нельзя»',
                    'володя шарапов': 'один из главных героев сериала «Место встречи изменить нельзя»',
                    'гуталина': 'вакса или крем для обуви',
                    'чёрная кошка': 'преступная группировка, орудовавшая в Москве и Московской области в начале 1950-х годов',
                }
            },
            {
                dayOfWeek: '22',
                artist: 'Иосиф Кобзон ',
                song: 'А у нас во дворе ',
                cover: 'https://assets.genius.com/images/default_cover_art.png?1714419001',
                youtube: 'http://www.youtube.com/watch?v=ztvJ4ry2gOs',
                date: '1962-07-15',
                geniusId: '7960538',
                definition: {
                    'булочной': 'магазин, торгующий хлебобулочными изделиями'
                }
            },
            {
                dayOfWeek: '23',
                artist: 'Стас Пьеха & Валерия ',
                song: 'Ты грустишь ',
                cover: 'https://images.genius.com/5bc4c0309245f6cda1376713cb968013.800x800x1.jpg',
                youtube: 'http://www.youtube.com/watch?v=TYOC-k6d9fc',
                date: '2005-01-01',
                geniusId: '9045491',
            },
            {
                dayOfWeek: '24',
                artist: 'Маша Распутина',
                song: 'Отпустите меня в Гималаи',
                cover: '',
                youtube: 'https://www.youtube.com/watch?v=eWCZmDYtlnY',
                date: '',
                geniusId: '366908',
                definition: {
                    'большевиков': 'радикальное крыло Российской социал-демократической рабочей партии после её раскола при II съезде РСДРП',
                    'диско': 'один из основных жанров танцевальной музыки XX века',
                    'ильичу': 'отчество Ленина',
                    'инфляции': 'устойчивое повышение общего уровня цен на товары и услуги',
                    'рок': 'музыкальный жанр и злая судьба',
                    'спида': 'синдром приобретённого иммунного дефицита',
                }
            },
            {
                dayOfWeek: '25',
                artist: 'Мистер Малой',
                song: 'Буду пАгибать мАлодым ',
                cover: 'https://images.genius.com/7257e10781b15cf6fea2d84fbfb239b3.1000x1000x1.jpg',
                youtube: 'http://www.youtube.com/watch?v=EII85QhntDM',
                date: '',
                geniusId: '3565212',
                definition: {
                    'ганджубас': 'марихуана',
                    'дринчи': '(сленг) пей',
                    'контрацептив': 'Противозачаточное средство',
                    'маузер': 'оружейная компания, основанная братьями Маузерами',
                    'распутин': 'фамилия сибирского крестьянина и водка',
                    'узи': 'ультразвуковое исследование',
                }
            },
            {
                dayOfWeek: '26',
                artist: 'Тутси ',
                song: 'Самый-самый ',
                cover: 'https://images.genius.com/5e0dec21ae8fa333daafa73e45f46551.500x500x1.jpg',
                youtube: 'http://www.youtube.com/watch?v=rJz5d7cAVfY',
                date: '2004-09-01',
                geniusId: '9107321',
                definition: {
                    'суббота': 'день недели',
                }
            },
            {
                dayOfWeek: '27',
                artist: 'FACE',
                song: 'ЮМОРИСТ ',
                cover: '',
                youtube: 'http://www.youtube.com/watch?v=NuXdxMEbYeQ',
                date: '2019-02-12',
                geniusId: '4306757',
                definition: {
                    'blacklist': '(англ.) черный список',
                    'gold': '(англ.) золото',
                    'my': '(англ.) мой, моя',
                    'on': '(англ.) на',
                    'pulpy': '(англ., бренд) Сокосодержащий напиток с сочной мякотью и кусочками фруктов',
                    'wrist': '(англ.) запястье',
                    'галкин': 'российский и израильский артист эстрады, пародист, юморист, шоумен',
                    'гулага': 'Главное управление исправительно-трудовых лагерей',
                    'маколей калкин': 'американский актёр кино, снявшийся в "Один дома"',
                    'санта': '(сокр.) Санта-Клаус',
                    'тайная вечеря': 'монументальная роспись работы Леонардо да Винчи, изображающая сцену последней трапезы Христа со своими учениками',
                }
            },
            {
                dayOfWeek: '28',
                artist: 'ЯНА ',
                song: 'Одинокий голубь ',
                cover: 'https://images.genius.com/9ae020fae2fc9f65d3a952a902265fb2.1000x1000x1.jpg',
                youtube: 'http://www.youtube.com/watch?v=LTgEqSQuGfM',
                date: '2018-12-30',
                geniusId: '4201934',
            },
            {
                dayOfWeek: '29',
                artist: 'Quest Pistols Show',
                song: 'Санта Лючия ',
                cover: '',
                youtube: 'http://www.youtube.com/watch?v=Q6a_mLhifqc',
                date: '2014-10-07',
                geniusId: '2237355',
                definition: {
                    'стробоскопа': 'прибор, позволяющий быстро воспроизводить повторяющиеся яркие световые импульсы',
                    'чили': 'страна и перец',
                }
            },
            {
                dayOfWeek: '30',
                artist: 'Nautilus Pompilius',
                song: 'Я хочу быть с тобой ',
                cover: 'https://images.genius.com/603c65de8733a776231a6d161ac73fd9.492x492x1.jpg',
                youtube: 'http://www.youtube.com/watch?v=0hYyKf4Lq4c',
                date: '',
                geniusId: '3035772',
            },
            {
                dayOfWeek: '31',
                artist: 'Мечтать',
                song: 'Лётчик',
                cover: 'https://images.genius.com/dea8e584340488b1280715f72f61eab7.1000x1000x1.jpg',
                youtube: 'http://www.youtube.com/watch?v=59qwN9ik5OY',
                date: '1996-01-01',
                geniusId: '6532233',
            },
        ],
    }
}