function getWeekSongs() {
    return {
        'ru': [
            {
                dayOfWeek: '1',
                artist: 'Ногу свело!',
                song: 'Хару мамбуру',
                cover: 'https://images.genius.com/75806a9e0a670cd1b75ccb045c4efec3.640x640x1.jpg',
                youtube: 'https://www.youtube.com/watch?v=VNKvtA9Akj',
                date: '',
                geniusId: '7611454',
            },
            {
                dayOfWeek: '2',
                artist: 'Маша и Медведи',
                song: 'Любочка',
                cover: 'https://images.genius.com/330f7ef386d677d0b25d2a727ac80bc8.1000x1000x1.jpg',
                youtube: 'http://www.youtube.com/watch?v=_e0mMPqXgwk',
                date: '',
                geniusId: '5482125',
                definition: {
                    'liebe': 'Любовь на немецком',
                    'amore': 'Любовь на итальянском'
                }
            },
            {
                dayOfWeek: '3',
                artist: 'Анжелика Варум',
                song: 'Ля-ля-фа',
                cover: '',
                youtube: 'https://www.youtube.com/watch?v=BnqpAKe_18Y',
                date: '',
                geniusId: '0',
                definition: {
                    'бульварах': 'Широкая аллея на городской улице, обычно посредине её.'
                }
            },
            {
                dayOfWeek: '4',
                artist: 'Сектор Газа',
                song: 'Лирика',
                cover: 'https://images.genius.com/0fdbc718a346d8afb384bb30e63d36e0.1000x1000x1.png',
                youtube: 'http://www.youtube.com/watch?v=etekDE13UKY',
                date: '',
                geniusId: '3969537',
            },
            {
                dayOfWeek: '5',
                artist: 'Юрий Шатунов',
                song: 'Седая ночь',
                cover: 'https://images.genius.com/afe51fb40509f5baf0c87a1212889c75.999x999x1.jpg',
                youtube: 'http://www.youtube.com/watch?v=MJMGAOR3NRo',
                date: '',
                geniusId: '4991597',
            },
            {
                dayOfWeek: '6',
                artist: 'CENTR',
                song: 'Город дорог ',
                cover: 'https://images.genius.com/bb91949d9ed646af421fa06aa55e2968.500x500x1.jpg',
                youtube: 'http://www.youtube.com/watch?v=peg2ocijmIQ',
                date: '2007-10-25',
                geniusId: '2958343',
                definition: {
                    'slim': 'Исполнитель песни',
                    'guf': 'Исполнитель песни',
                    'аэрофлота': 'российская государственно-частная авиакомпания',
                    'екх': 'номера, предназначенные для автомобилей ФСО РФ',
                }
            },
            {
                dayOfWeek: '7',
                artist: 'Дюна',
                song: 'Море пива',
                cover: '',
                youtube: 'https://www.youtube.com/watch?v=pHMJKqLYO5A',
                date: '',
                geniusId: '0',
                definition: {
                    'c2h5oh': 'Химичиский состав этанола',
                }
            },
            {
                dayOfWeek: '8',
                artist: 'Ирина Салтыкова',
                song: 'Серые глаза',
                cover: 'https://images.genius.com/b2d06038056c6c8ce9587c28938cd180.640x640x1.jpg',
                youtube: 'https://www.youtube.com/watch?v=J9KzfyUR78c',
                date: '',
                geniusId: '4733576',
            },
            {
                dayOfWeek: '9',
                artist: 'SLAVA MARLOW',
                song: 'Снова я напиваюсь',
                cover: 'https://images.genius.com/b66090fe9693e90483f0fc210e997d40.1000x1000x1.png',
                youtube: 'http://www.youtube.com/watch?v=hQ71f7dFj6Y',
                date: '2020-10-07',
                geniusId: '5944117',
            },
            {
                dayOfWeek: '10',
                artist: 'Несчастный Случай',
                song: 'Генералы песчаных карьеров',
                cover: 'https://images.genius.com/1bb6d5953d6bc231084f78ab3a977358.598x598x1.jpg',
                youtube: 'http://www.youtube.com/watch?v=r3KJMAi04fM',
                date: '',
                geniusId: '4300344',
            },
            {
                dayOfWeek: '11',
                artist: 'Наталья Ветлицкая',
                song: 'Посмотри в глаза',
                cover: 'https://images.genius.com/5231121a6584c52db75e0743fb112ebb.640x640x1.jpg',
                youtube: 'http://www.youtube.com/watch?v=hAPVpywbbW0',
                date: '',
                geniusId: '4630082',
            },
            {
                dayOfWeek: '12',
                artist: 'Женя Белоусов',
                song: 'Девчонка-девчоночка',
                cover: '',
                youtube: 'https://www.youtube.com/watch?v=pXNdRdcN_Ig',
                date: '',
                geniusId: '4592110',
            },
            {
                dayOfWeek: '13',
                artist: 'Машина Времени ',
                song: 'Поворот ',
                cover: 'https://assets.genius.com/images/default_cover_art.png?1710963199',
                youtube: 'http://www.youtube.com/watch?v=knxWqM86t5w',
                date: '',
                geniusId: '3873948',
            },
            {
                dayOfWeek: '14',
                artist: 'Порнофильмы',
                song: 'Молодость',
                cover: 'https://images.genius.com/7dcc9b903695e47eb3c488f0233dd090.1000x1000x1.jpg',
                youtube: 'https://www.youtube.com/watch?v=Q5th-hzPOhA',
                date: '2014-03-29',
                geniusId: '5298732',
                definition: {
                    'панк-рок': 'музыкальный стиль',
                    'психдиспансеры': 'специализированное медицинское учреждение',

                }
            },
            {
                dayOfWeek: '15',
                artist: 'Noize MC',
                song: 'Всё как у людей',
                cover: 'https://images.genius.com/e346d349260bc6f5f56ab9555e323aec.1000x1000x1.jpg',
                youtube: 'http://www.youtube.com/watch?v=eLAHSRmFFzE',
                date: '2019-09-10',
                geniusId: '4856014',
                definition: {
                    'lego': 'конструктор родом из Дании',
                    'ми-6': 'английская разведка',
                    'челубей': 'персонаж «Сказания о Мамаевом побоище»',
                }
            },
            {
                dayOfWeek: '16',
                artist: 'Юлия Савичева',
                song: 'Если в сердце живёт любовь',
                cover: '',
                youtube: 'http://www.youtube.com/watch?v=XSI99eTsfnU',
                date: '2005-09-03',
                geniusId: '3158735',
            },
            {
                dayOfWeek: '17',
                artist: 'Бумбокс',
                song: 'Вахтерам',
                cover: 'https://images.genius.com/575767bf8133b11d7a712ae76926be31.1000x1000x1.jpg',
                youtube: 'http://www.youtube.com/watch?v=ltFfe10pz3A',
                date: '2006-06-22',
                geniusId: '2237167',
                definition: {
                    'fm': 'радио-термин, частотная модулация',
                }
            },
            {
                dayOfWeek: '18',
                artist: 'Валерий Сюткин',
                song: 'Я - То, Что Надо',
                cover: 'https://images.genius.com/ce3c0e352263bc151f1e5f7c252f87db.828x828x1.jpg',
                youtube: 'https://www.youtube.com/watch?v=ayh_v_ZVFzk',
                date: '',
                geniusId: '5313200',
            },
            {
                dayOfWeek: '19',
                artist: 'Наташа Королёва',
                song: 'Жёлтые тюльпаны',
                cover: 'https://images.genius.com/3d09fa9fa2163d09584a4683d0ff9078.1000x1000x1.jpg',
                youtube: 'http://www.youtube.com/watch?v=h9nhOEdXRfI',
                date: '',
                geniusId: '8907741',
            },
            {
                dayOfWeek: '20',
                artist: 'Игорь Скляр',
                song: 'Комарово',
                cover: 'https://images.genius.com/864654c915c0a8d4e1dc9f1ff7eb2972.594x594x1.jpg',
                youtube: 'https://www.youtube.com/watch?v=YPw9sZbFEeo',
                date: '',
                geniusId: '5219320',
                definition: {
                    'шереметьевский': 'прилогательное (как и московский аэропорт) образованое от фамилии русского графа',
                    'шереметьевский': 'прилогательное образованое от названия субъекта (республика) Российской Федерации',
                }
            },
            {
                dayOfWeek: '21',
                artist: 'Нэнси',
                song: 'Дым сигарет с ментолом',
                cover: 'https://images.genius.com/fb52db9ef1d6a9cf235ea975d6b43eb5.936x936x1.jpg',
                youtube: 'http://www.youtube.com/watch?v=6J5kwV_gpeA',
                date: '',
                geniusId: '4428158',
            },
            {
                dayOfWeek: '22',
                artist: 'Иосиф Кобзон',
                song: 'И вновь продолжается бой',
                cover: 'https://images.genius.com/5e144e57027ffa82aaba0062bea2bf11.1000x1000x1.png',
                youtube: 'http://www.youtube.com/watch?v=vhXGQ4G8cG8',
                date: '1975-07-15',
                geniusId: '7955046',
                definition: {
                    'стяг': 'то же, что и знамя',
                    'октябрь': 'осенний месяц',
                    'стройотряд': 'студенческий строительный отряд',
                }
            },
            {
                dayOfWeek: '23',
                artist: 'Dabro',
                song: 'Юность',
                cover: 'https://images.genius.com/35e4b6c176ee661cd3db32f688d2ce1a.1000x1000x1.png',
                youtube: 'https://www.youtube.com/watch?v=aqsgyOhrRMY',
                date: '2020-05-15',
                geniusId: '5570053',
                definition: {
                    'dabro': 'название групы',
                }
            },
            {
                dayOfWeek: '24',
                artist: 'Белый орёл',
                song: 'Как упоительны в России вечера',
                cover: '',
                youtube: 'https://www.youtube.com/watch?v=BQ_E520lhAI',
                date: '',
                geniusId: '0',
                definition: {
                    'юнкера': 'воинское звание в Русских гвардии и армии, до 1918 года, промежуточное по своему правовому статусу между унтер-офицерами и обер-офицерами.',
                    'Шуберта': 'австрийский композитор',
                }
            },
            {
                dayOfWeek: '25',
                artist: 'Король и Шут',
                song: 'Кукла колдуна',
                cover: 'https://images.genius.com/72b8e793ae6943cdf5aaa0f198a31118.1000x1000x1.png',
                youtube: 'https://www.youtube.com/watch?v=4kAMK1SbYKM',
                date: '',
                geniusId: '4407199',
            },
            {
                dayOfWeek: '26',
                artist: 'Родион Газманов',
                song: 'Люси',
                cover: '',
                youtube: 'https://www.youtube.com/watch?v=msMS7dRRB2E',
                date: '1991-00-04',
                geniusId: '',
            },
            {
                dayOfWeek: '27',
                artist: 'Мумий Тролль',
                song: 'Владивосток 2000',
                cover: 'https://images.genius.com/712956cb800356bc0c9a406bb58d354a.900x896x1.jpg',
                youtube: 'http://www.youtube.com/watch?v=nj5nuYYrZvg',
                date: '1997-04-24',
                geniusId: '2898404',
                definition: {
                    'круизер': 'разновидность мотоциклов, отличающаяся низким сиденьем, вертикальной посадкой'
                }
            },
            {
                dayOfWeek: '28',
                artist: 'Лесоповал',
                song: 'Я Куплю Тебе Дом',
                cover: 'https://images.genius.com/bf28efb28788d0195b2b7d2c2c9c47fa.999x999x1.jpg',
                youtube: 'https://www.youtube.com/watch?v=ufqGZQjXbj8',
                date: '',
                geniusId: '4514366',
                definition: {
                    'сирень': 'род кустарников, принадлежащий семейству Маслиновые'
                }
            },
            {
                dayOfWeek: '29',
                artist: 'Михаил Боярский',
                song: 'Зеленоглазое такси',
                cover: '',
                youtube: 'https://www.youtube.com/watch?v=7FYCYy3lxrI',
                date: '',
                geniusId: '4132294',
            },
            {
                dayOfWeek: '30',
                artist: 'Олег Газманов',
                song: 'Морячка',
                cover: 'https://images.genius.com/93a2d2075ee016f135eb78af9c0a453e.1000x1000x1.jpg',
                youtube: 'https://www.youtube.com/watch?v=CdCCjL0BbY8',
                date: '',
                geniusId: '8593317',
                definition: {
                    'лебедка': 'механизм, тяговое усилие которого передаётся посредством каната, цепи, троса или иного гибкого элемента от приводного барабана.',
                    'трал': 'Большая сеть в форме мешка для ловли рыбы с судов',
                    'швартовые': 'синтетические или стальные тросы, которые крепять к причальной стенке, пирсу или другому судну.',
                    'кнехты': 'парная тумба с общим основанием на палубе судна, служащая для крепления тросов',
                }
            },
        ],
        'en': [
            {
                dayOfWeek: '1',
                artist: 'The Prodigy',
                song: 'Smack My Bitch Up',
                cover: 'https://images.genius.com/1ff9d8c55e245ed203af7dd67501af22.1000x1000x1.png',
                youtube: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                date: '1997-11-17',
                geniusId: '134900',
            },
            {
                dayOfWeek: '2',
                artist: 'Eiffel 65',
                song: 'Blue ',
                cover: 'https://images.genius.com/2304d8be6b698b3c90e0102fda5d957f.633x633x1.jpg',
                youtube: 'http://www.youtube.com/watch?v=68ugkg9RePc',
                date: '1999-11-30',
                geniusId: '57225',
            },
            {
                dayOfWeek: '3',
                artist: 'Akon ',
                song: 'I Wanna Love You',
                cover: 'https://images.genius.com/6f94838f2c084d982159f8e602b808b4.640x640x1.jpg',
                youtube: 'http://www.youtube.com/watch?v=GJzF7H2e3Tw',
                date: '2006-09-14',
                geniusId: '177239',
            },
            {
                dayOfWeek: '4',
                artist: 'Cher',
                song: 'Believe',
                cover: 'https://images.genius.com/4413477f422acb83c13329ee11a14d36.1000x1000x1.jpg',
                youtube: 'http://www.youtube.com/watch?v=nZXRV4MezEw',
                date: '1998-10-19',
                geniusId: '176588',
            },
            {
                dayOfWeek: '5',
                artist: 'Backstreet Boys',
                song: 'Everybody ',
                cover: 'https://images.genius.com/e74c1c5d5c57a3fe24b017cc5f9f56a1.600x600x1.jpg',
                youtube: 'http://www.youtube.com/watch?v=6M6samPEMpM',
                date: '1997-06-30',
                geniusId: '176484',
            },
            {
                dayOfWeek: '6',
                artist: 'Dead or Alive',
                song: 'You Spin Me Round ',
                cover: 'https://images.genius.com/ae061f15f57e1157563c0b979386ee2e.600x600x1.jpg',
                youtube: 'http://www.youtube.com/watch?v=PGNiXGX2nLU',
                date: '1984-11-05',
                geniusId: '787799',
            },
            {
                dayOfWeek: '7',
                artist: 'The Cure',
                song: 'Friday I’m in Love',
                cover: 'https://images.genius.com/7814bb6d842d949c8cbfc0086f02d312.1000x1000x1.jpg',
                youtube: 'http://www.youtube.com/watch?v=Dt7oMSOB7nw',
                date: '1992-05-11',
                geniusId: '388590',
            },
            {
                dayOfWeek: '8',
                artist: 'The Mamas & The Papas',
                song: 'Dream a Little Dream of Me',
                cover: 'https://images.genius.com/f16c38c35883e1c8309e6e1102c8911c.300x300x1.jpg',
                youtube: 'http://www.youtube.com/watch?v=v8I5vDewcZo',
                date: '',
                geniusId: '773414',
            },
            {
                dayOfWeek: '9',
                artist: 'Reamonn',
                song: 'Tonight',
                cover: 'https://images.genius.com/aa03d874f59319e7eccf4f73f59dfdfa.1000x1000x1.jpg',
                youtube: 'http://www.youtube.com/watch?v=jtoncUzV6nA',
                date: '2006-07-07',
                geniusId: '899852',
            },
            {
                dayOfWeek: '10',
                artist: 'Justin Timberlake ',
                song: 'SexyBack',
                cover: 'https://images.genius.com/e41fd6b69a6a4904e3334c48d7549909.1000x1000x1.jpg',
                youtube: 'http://www.youtube.com/watch?v=3gOHvDP_vCs',
                date: '2006-07-18',
                geniusId: '32771',
            },
            {
                dayOfWeek: '11',
                artist: 'Alice Cooper',
                song: 'Poison',
                cover: 'https://images.genius.com/31a7d07007eec297bdf885ed0443be28.848x848x1.png',
                youtube: 'http://www.youtube.com/watch?v=Qq4j1LtCdww',
                date: '1989-01-01',
                geniusId: '413757',
            },
            {
                dayOfWeek: '12',
                artist: 'The Weather Girls',
                song: 'It’s Raining Men',
                cover: 'https://images.genius.com/aa93bad2bedde6f6cb25caf43e71e87e.591x591x1.jpg',
                youtube: 'http://www.youtube.com/watch?v=l5aZJBLAu1E',
                date: '1982-09-10',
                geniusId: '111549',
            },
            {
                dayOfWeek: '13',
                artist: 'Crazy Town',
                song: 'Butterfly',
                cover: 'https://images.genius.com/9516f76c1ef84f09d665bee0b7fe8be0.640x640x1.png',
                youtube: 'http://www.youtube.com/watch?v=6FEDrU85FLE',
                date: '1999-10-26',
                geniusId: '49660',
            },
            {
                dayOfWeek: '14',
                artist: 'Radiohead',
                song: 'Creep',
                cover: 'https://images.genius.com/93547fe5db0ba8a10d9885edbab10a7d.1000x1000x1.jpg',
                youtube: 'http://www.youtube.com/watch?v=XFkzRNyygfk',
                date: '1992-09-21',
                geniusId: '109096',
            },
            {
                dayOfWeek: '15',
                artist: 'Modern Talking',
                song: 'You’re My Heart, You’re My Soul',
                cover: 'https://images.genius.com/24e42d72ef88256447de70c0ade40d10.1000x1000x1.jpg',
                youtube: 'http://www.youtube.com/watch?v=4kHl4FoK1Ys',
                date: '1984-10-29',
                geniusId: '2263984',
            },
            {
                dayOfWeek: '16',
                artist: 'Nelly Furtado',
                song: 'Say It Right',
                cover: 'https://images.genius.com/60c845fd87d70b0dabb9192805646445.1000x1000x1.png',
                youtube: 'http://www.youtube.com/watch?v=6JnGBs88sL0',
                date: '2006-10-30',
                geniusId: '62177',
            },
            {
                dayOfWeek: '17',
                artist: 'Eurythmics',
                song: 'Sweet Dreams ',
                cover: 'https://images.genius.com/f0ceb005ed3db23cde8fc3d0fba1cb0f.561x561x1.jpg',
                youtube: 'http://www.youtube.com/watch?v=qeMFqkcPYcg',
                date: '1983-01-21',
                geniusId: '1640',
            },
            {
                dayOfWeek: '18',
                artist: 'Whitney Houston',
                song: 'I Will Always Love You',
                cover: 'https://images.genius.com/5afaabd091ea68bde262c8fb98f2ea64.1000x1000x1.jpg',
                youtube: 'http://www.youtube.com/watch?v=3JWTaaS7LdU',
                date: '1992-11-03',
                geniusId: '329470',
            },
            {
                dayOfWeek: '19',
                artist: 'Nirvana',
                song: 'Smells Like Teen Spirit',
                cover: 'https://images.genius.com/c7a0f0fae1f28e4cd3982e5779574f81.1000x1000x1.png',
                youtube: 'http://www.youtube.com/watch?v=hTWKbfoikeg',
                date: '1991-09-10',
                geniusId: '52968',
            },
            {
                dayOfWeek: '20',
                artist: 'LeAnn Rimes',
                song: 'Can’t Fight the Moonlight',
                cover: 'https://images.genius.com/8658b4668a55e7fed3f7d09ce31357b3.1000x1000x1.jpg',
                youtube: 'http://www.youtube.com/watch?v=bx3s99FNXzI',
                date: '2000-08-22',
                geniusId: '590722',
            },
            {
                dayOfWeek: '21',
                artist: 'Nickelback',
                song: 'How You Remind Me',
                cover: 'https://images.genius.com/8eb5ebf6dd5d681cf8accc33c65dcaf7.1000x1000x1.jpg',
                youtube: 'http://www.youtube.com/watch?v=1cQh1ccqu8M',
                date: '2001-08-21',
                geniusId: '196442',
            },
            {
                dayOfWeek: '22',
                artist: '50 Cent',
                song: 'In da Club',
                cover: 'https://images.genius.com/2f71a968b8b2b666a070c291edcf300e.1000x1000x1.png',
                youtube: 'http://www.youtube.com/watch?v=5qm8PH4xAss',
                date: '2003-01-07',
                geniusId: '233',
            },
            {
                dayOfWeek: '23',
                artist: 'Gnarls Barkley',
                song: 'Crazy',
                cover: 'https://images.genius.com/af189376114da3e096c3d8bbe035dcf4.600x600x1.jpg',
                youtube: 'http://www.youtube.com/watch?v=-N4jf6rtyuw',
                date: '2006-04-04',
                geniusId: '21248',
            },
            {
                dayOfWeek: '24',
                artist: 'The Cardigans',
                song: 'My Favourite Game',
                cover: 'https://images.genius.com/b8cca56bf3337c3693a90a3c2d5c67cd.600x600x1.jpg',
                youtube: 'http://www.youtube.com/watch?v=6Ll5y2hZdCI',
                date: '1998-10-01',
                geniusId: '379175',
            },
            {
                dayOfWeek: '25',
                artist: 'Geri Halliwell',
                song: 'Mi Chico Latino',
                cover: 'https://images.genius.com/891da846152fd36f9f45c282fc7dcf0e.1000x1000x1.png',
                youtube: 'http://www.youtube.com/watch?v=XgoKfHg1JsU',
                date: '1999-08-16',
                geniusId: '988686',
            },
            {
                dayOfWeek: '26',
                artist: 'Paris Hilton',
                song: 'Stars Are Blind',
                cover: 'https://images.genius.com/f3ac8284ef4d145bc876c843455d4d4b.1000x1000x1.jpg',
                youtube: 'http://www.youtube.com/watch?v=6Mj776YiPCU',
                date: '2006-06-05',
                geniusId: '368198',
            },
            {
                dayOfWeek: '27',
                artist: 'Kylie Minogue',
                song: 'Can’t Get You Out Of My Head',
                cover: 'https://images.genius.com/82f2230b04d8378738f4002901c922d6.591x591x1.jpg',
                youtube: 'http://www.youtube.com/watch?v=c18441Eh_WE',
                date: '2001-09-08',
                geniusId: '121287',
            },
            {
                dayOfWeek: '28',
                artist: 'Rick Astley',
                song: 'Never Gonna Give You Up',
                cover: 'https://images.genius.com/190ed514eddd2032090f8943ec438af5.600x600x1.jpg',
                youtube: 'http://www.youtube.com/watch?v=dQw4w9WgXcQ',
                date: '1987-07-27',
                geniusId: '84851',
            },
            {
                dayOfWeek: '29',
                artist: 'Michael Jackson',
                song: 'Billie Jean',
                cover: 'https://images.genius.com/40e641595079538a692b50fcd9bde72b.1000x1000x1.jpg',
                youtube: 'http://www.youtube.com/watch?v=Zi_XLOBDo_Y',
                date: '1982-11-30',
                geniusId: '1644',
            },
            {
                dayOfWeek: '30',
                artist: 'Eagles',
                song: 'Hotel California',
                cover: 'https://images.genius.com/8106bf7f48102194b21031f0a8b2bb19.956x956x1.jpg',
                youtube: 'http://www.youtube.com/watch?v=09839DpTctU',
                date: '1976-12-08',
                geniusId: '1060',
                definition: {
                    '1969': 'Year of Woodstock Festival'
                }
            },
        ],
    }
}